// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/com/javafxbindingtest/contracts/weather.proto
// Protobuf Java Version: 4.33.1

package com.javafxbindingtest.proto;

/**
 * Protobuf type {@code weather.WeatherInfo}
 */
@com.google.protobuf.Generated
public final class WeatherInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:weather.WeatherInfo)
    WeatherInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "WeatherInfo");
  }
  // Use WeatherInfo.newBuilder() to construct.
  private WeatherInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private WeatherInfo() {
    condition_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.javafxbindingtest.proto.WeatherProto.internal_static_weather_WeatherInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.javafxbindingtest.proto.WeatherProto.internal_static_weather_WeatherInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.javafxbindingtest.proto.WeatherInfo.class, com.javafxbindingtest.proto.WeatherInfo.Builder.class);
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 1;
  private double temperature_ = 0D;
  /**
   * <code>double temperature = 1;</code>
   * @return The temperature.
   */
  @java.lang.Override
  public double getTemperature() {
    return temperature_;
  }

  public static final int WINDSPEED_FIELD_NUMBER = 2;
  private double windSpeed_ = 0D;
  /**
   * <code>double windSpeed = 2;</code>
   * @return The windSpeed.
   */
  @java.lang.Override
  public double getWindSpeed() {
    return windSpeed_;
  }

  public static final int HUMIDITY_FIELD_NUMBER = 3;
  private double humidity_ = 0D;
  /**
   * <code>double humidity = 3;</code>
   * @return The humidity.
   */
  @java.lang.Override
  public double getHumidity() {
    return humidity_;
  }

  public static final int PRESSURE_FIELD_NUMBER = 4;
  private double pressure_ = 0D;
  /**
   * <code>double pressure = 4;</code>
   * @return The pressure.
   */
  @java.lang.Override
  public double getPressure() {
    return pressure_;
  }

  public static final int CONDITION_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object condition_ = "";
  /**
   * <code>string condition = 5;</code>
   * @return The condition.
   */
  @java.lang.Override
  public java.lang.String getCondition() {
    java.lang.Object ref = condition_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      condition_ = s;
      return s;
    }
  }
  /**
   * <code>string condition = 5;</code>
   * @return The bytes for condition.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConditionBytes() {
    java.lang.Object ref = condition_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      condition_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALERT_FIELD_NUMBER = 6;
  private boolean alert_ = false;
  /**
   * <code>bool alert = 6;</code>
   * @return The alert.
   */
  @java.lang.Override
  public boolean getAlert() {
    return alert_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(temperature_) != 0) {
      output.writeDouble(1, temperature_);
    }
    if (java.lang.Double.doubleToRawLongBits(windSpeed_) != 0) {
      output.writeDouble(2, windSpeed_);
    }
    if (java.lang.Double.doubleToRawLongBits(humidity_) != 0) {
      output.writeDouble(3, humidity_);
    }
    if (java.lang.Double.doubleToRawLongBits(pressure_) != 0) {
      output.writeDouble(4, pressure_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(condition_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, condition_);
    }
    if (alert_ != false) {
      output.writeBool(6, alert_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(temperature_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, temperature_);
    }
    if (java.lang.Double.doubleToRawLongBits(windSpeed_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, windSpeed_);
    }
    if (java.lang.Double.doubleToRawLongBits(humidity_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, humidity_);
    }
    if (java.lang.Double.doubleToRawLongBits(pressure_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, pressure_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(condition_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, condition_);
    }
    if (alert_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, alert_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.javafxbindingtest.proto.WeatherInfo)) {
      return super.equals(obj);
    }
    com.javafxbindingtest.proto.WeatherInfo other = (com.javafxbindingtest.proto.WeatherInfo) obj;

    if (java.lang.Double.doubleToLongBits(getTemperature())
        != java.lang.Double.doubleToLongBits(
            other.getTemperature())) return false;
    if (java.lang.Double.doubleToLongBits(getWindSpeed())
        != java.lang.Double.doubleToLongBits(
            other.getWindSpeed())) return false;
    if (java.lang.Double.doubleToLongBits(getHumidity())
        != java.lang.Double.doubleToLongBits(
            other.getHumidity())) return false;
    if (java.lang.Double.doubleToLongBits(getPressure())
        != java.lang.Double.doubleToLongBits(
            other.getPressure())) return false;
    if (!getCondition()
        .equals(other.getCondition())) return false;
    if (getAlert()
        != other.getAlert()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTemperature()));
    hash = (37 * hash) + WINDSPEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWindSpeed()));
    hash = (37 * hash) + HUMIDITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getHumidity()));
    hash = (37 * hash) + PRESSURE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPressure()));
    hash = (37 * hash) + CONDITION_FIELD_NUMBER;
    hash = (53 * hash) + getCondition().hashCode();
    hash = (37 * hash) + ALERT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAlert());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.javafxbindingtest.proto.WeatherInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.javafxbindingtest.proto.WeatherInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.javafxbindingtest.proto.WeatherInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.javafxbindingtest.proto.WeatherInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.javafxbindingtest.proto.WeatherInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.javafxbindingtest.proto.WeatherInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.javafxbindingtest.proto.WeatherInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.javafxbindingtest.proto.WeatherInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.javafxbindingtest.proto.WeatherInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.javafxbindingtest.proto.WeatherInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.javafxbindingtest.proto.WeatherInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.javafxbindingtest.proto.WeatherInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.javafxbindingtest.proto.WeatherInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code weather.WeatherInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:weather.WeatherInfo)
      com.javafxbindingtest.proto.WeatherInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.javafxbindingtest.proto.WeatherProto.internal_static_weather_WeatherInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.javafxbindingtest.proto.WeatherProto.internal_static_weather_WeatherInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.javafxbindingtest.proto.WeatherInfo.class, com.javafxbindingtest.proto.WeatherInfo.Builder.class);
    }

    // Construct using com.javafxbindingtest.proto.WeatherInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      temperature_ = 0D;
      windSpeed_ = 0D;
      humidity_ = 0D;
      pressure_ = 0D;
      condition_ = "";
      alert_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.javafxbindingtest.proto.WeatherProto.internal_static_weather_WeatherInfo_descriptor;
    }

    @java.lang.Override
    public com.javafxbindingtest.proto.WeatherInfo getDefaultInstanceForType() {
      return com.javafxbindingtest.proto.WeatherInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.javafxbindingtest.proto.WeatherInfo build() {
      com.javafxbindingtest.proto.WeatherInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.javafxbindingtest.proto.WeatherInfo buildPartial() {
      com.javafxbindingtest.proto.WeatherInfo result = new com.javafxbindingtest.proto.WeatherInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.javafxbindingtest.proto.WeatherInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.temperature_ = temperature_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.windSpeed_ = windSpeed_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.humidity_ = humidity_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.pressure_ = pressure_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.condition_ = condition_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.alert_ = alert_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.javafxbindingtest.proto.WeatherInfo) {
        return mergeFrom((com.javafxbindingtest.proto.WeatherInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.javafxbindingtest.proto.WeatherInfo other) {
      if (other == com.javafxbindingtest.proto.WeatherInfo.getDefaultInstance()) return this;
      if (java.lang.Double.doubleToRawLongBits(other.getTemperature()) != 0) {
        setTemperature(other.getTemperature());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getWindSpeed()) != 0) {
        setWindSpeed(other.getWindSpeed());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getHumidity()) != 0) {
        setHumidity(other.getHumidity());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getPressure()) != 0) {
        setPressure(other.getPressure());
      }
      if (!other.getCondition().isEmpty()) {
        condition_ = other.condition_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getAlert() != false) {
        setAlert(other.getAlert());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              temperature_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              windSpeed_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              humidity_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              pressure_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 42: {
              condition_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              alert_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double temperature_ ;
    /**
     * <code>double temperature = 1;</code>
     * @return The temperature.
     */
    @java.lang.Override
    public double getTemperature() {
      return temperature_;
    }
    /**
     * <code>double temperature = 1;</code>
     * @param value The temperature to set.
     * @return This builder for chaining.
     */
    public Builder setTemperature(double value) {

      temperature_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>double temperature = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTemperature() {
      bitField0_ = (bitField0_ & ~0x00000001);
      temperature_ = 0D;
      onChanged();
      return this;
    }

    private double windSpeed_ ;
    /**
     * <code>double windSpeed = 2;</code>
     * @return The windSpeed.
     */
    @java.lang.Override
    public double getWindSpeed() {
      return windSpeed_;
    }
    /**
     * <code>double windSpeed = 2;</code>
     * @param value The windSpeed to set.
     * @return This builder for chaining.
     */
    public Builder setWindSpeed(double value) {

      windSpeed_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double windSpeed = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWindSpeed() {
      bitField0_ = (bitField0_ & ~0x00000002);
      windSpeed_ = 0D;
      onChanged();
      return this;
    }

    private double humidity_ ;
    /**
     * <code>double humidity = 3;</code>
     * @return The humidity.
     */
    @java.lang.Override
    public double getHumidity() {
      return humidity_;
    }
    /**
     * <code>double humidity = 3;</code>
     * @param value The humidity to set.
     * @return This builder for chaining.
     */
    public Builder setHumidity(double value) {

      humidity_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double humidity = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHumidity() {
      bitField0_ = (bitField0_ & ~0x00000004);
      humidity_ = 0D;
      onChanged();
      return this;
    }

    private double pressure_ ;
    /**
     * <code>double pressure = 4;</code>
     * @return The pressure.
     */
    @java.lang.Override
    public double getPressure() {
      return pressure_;
    }
    /**
     * <code>double pressure = 4;</code>
     * @param value The pressure to set.
     * @return This builder for chaining.
     */
    public Builder setPressure(double value) {

      pressure_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double pressure = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPressure() {
      bitField0_ = (bitField0_ & ~0x00000008);
      pressure_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object condition_ = "";
    /**
     * <code>string condition = 5;</code>
     * @return The condition.
     */
    public java.lang.String getCondition() {
      java.lang.Object ref = condition_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        condition_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string condition = 5;</code>
     * @return The bytes for condition.
     */
    public com.google.protobuf.ByteString
        getConditionBytes() {
      java.lang.Object ref = condition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        condition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string condition = 5;</code>
     * @param value The condition to set.
     * @return This builder for chaining.
     */
    public Builder setCondition(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      condition_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string condition = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCondition() {
      condition_ = getDefaultInstance().getCondition();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string condition = 5;</code>
     * @param value The bytes for condition to set.
     * @return This builder for chaining.
     */
    public Builder setConditionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      condition_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private boolean alert_ ;
    /**
     * <code>bool alert = 6;</code>
     * @return The alert.
     */
    @java.lang.Override
    public boolean getAlert() {
      return alert_;
    }
    /**
     * <code>bool alert = 6;</code>
     * @param value The alert to set.
     * @return This builder for chaining.
     */
    public Builder setAlert(boolean value) {

      alert_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool alert = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlert() {
      bitField0_ = (bitField0_ & ~0x00000020);
      alert_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:weather.WeatherInfo)
  }

  // @@protoc_insertion_point(class_scope:weather.WeatherInfo)
  private static final com.javafxbindingtest.proto.WeatherInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.javafxbindingtest.proto.WeatherInfo();
  }

  public static com.javafxbindingtest.proto.WeatherInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WeatherInfo>
      PARSER = new com.google.protobuf.AbstractParser<WeatherInfo>() {
    @java.lang.Override
    public WeatherInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WeatherInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WeatherInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.javafxbindingtest.proto.WeatherInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

