// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/com/javafxbindingtest/contracts/weather.proto
// Protobuf Java Version: 4.33.1

package com.javafxbindingtest.proto;

@com.google.protobuf.Generated
public interface WeatherInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weather.WeatherInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double temperature = 1;</code>
   * @return The temperature.
   */
  double getTemperature();

  /**
   * <code>double windSpeed = 2;</code>
   * @return The windSpeed.
   */
  double getWindSpeed();

  /**
   * <code>double humidity = 3;</code>
   * @return The humidity.
   */
  double getHumidity();

  /**
   * <code>double pressure = 4;</code>
   * @return The pressure.
   */
  double getPressure();

  /**
   * <code>string condition = 5;</code>
   * @return The condition.
   */
  java.lang.String getCondition();
  /**
   * <code>string condition = 5;</code>
   * @return The bytes for condition.
   */
  com.google.protobuf.ByteString
      getConditionBytes();

  /**
   * <code>bool alert = 6;</code>
   * @return The alert.
   */
  boolean getAlert();
}
