// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/com/javafxbindingtest/contracts/weather.proto
// Protobuf Java Version: 4.33.1

package com.javafxbindingtest.proto;

@com.google.protobuf.Generated
public final class WeatherProto extends com.google.protobuf.GeneratedFile {
  private WeatherProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "WeatherProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weather_WeatherInfoProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_weather_WeatherInfoProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<src/main/proto/com/javafxbindingtest/c" +
      "ontracts/weather.proto\022\007weather\"\245\001\n\020Weat" +
      "herInfoProto\022\023\n\013temperature\030\001 \001(\001\022\021\n\twin" +
      "dSpeed\030\002 \001(\001\022\020\n\010humidity\030\003 \001(\001\022\020\n\010pressu" +
      "re\030\004 \001(\001\022\021\n\tcondition\030\005 \001(\t\022\r\n\005alert\030\006 \001" +
      "(\010\022\020\n\010latitude\030\007 \001(\001\022\021\n\tlongitude\030\010 \001(\001B" +
      "-\n\033com.javafxbindingtest.protoB\014WeatherP" +
      "rotoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_weather_WeatherInfoProto_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_weather_WeatherInfoProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_weather_WeatherInfoProto_descriptor,
        new java.lang.String[] { "Temperature", "WindSpeed", "Humidity", "Pressure", "Condition", "Alert", "Latitude", "Longitude", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
